# Generated by Django 2.0.2 on 2018-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data published')),
                ('primeiro_tempo', models.IntegerField(default=0)),
                ('segundo_tempo', models.IntegerField(default=0)),
                ('terceiro_tempo', models.IntegerField(default=0)),
                ('quarto_tempo', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
