# Generated by Django 2.0.2 on 2018-05-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedicao', '0002_expedicao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedicao',
            name='ano',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='dia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expedicao',
            name='mes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
