# Generated by Django 2.0.2 on 2018-05-15 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comportamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='date published')),
                ('ordens', models.IntegerField(default=0)),
                ('celular', models.IntegerField(default=0)),
                ('pausa_indev', models.IntegerField(default=0)),
                ('banco', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Erros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='date published')),
                ('data_pedido', models.DateField(verbose_name='date published')),
                ('pedido', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('erro', models.CharField(max_length=200)),
                ('conta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(1, 2)], default=1)),
                ('med_comportamento', models.FloatField(default=0)),
                ('med_erros', models.FloatField(default=0)),
                ('med_rendimento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='date published')),
                ('total_diario', models.IntegerField(default=0)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='erros',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
        migrations.AddField(
            model_name='erros',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comportamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
        migrations.AddField(
            model_name='comportamento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
