# Generated by Django 2.0.2 on 2018-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20180514_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erros',
            name='conta',
            field=models.IntegerField(default=0),
        ),
    ]
