# Generated by Django 2.0.2 on 2018-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20180514_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimento',
            name='data',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
