# Generated by Django 2.0.2 on 2018-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20180515_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimento',
            name='data',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
