# Generated by Django 2.0.2 on 2018-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20180515_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimento',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='dia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='mes',
            field=models.IntegerField(null=True),
        ),
    ]
