# Generated by Django 2.0.2 on 2018-05-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_auto_20180515_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimento',
            name='ano',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rendimento',
            name='dia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rendimento',
            name='mes',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
