# Generated by Django 2.0.2 on 2018-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_auto_20180515_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comportamento',
            name='media',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='banco',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='celular',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='ordens',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='pausa_indev',
            field=models.IntegerField(default=5),
        ),
    ]
