# Generated by Django 2.0.2 on 2018-05-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_auto_20180516_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='med_erros',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_brinde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_etiqueta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_falta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_sabor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_troca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='erro_vencido',
            field=models.IntegerField(default=0),
        ),
    ]
