# Generated by Django 2.0.2 on 2018-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_auto_20180516_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='erros_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_brinde',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_etiqueta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_falta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_sabor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_troca',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='porcentagem_vencido',
            field=models.FloatField(default=0),
        ),
    ]
